name: arc-rest
version: 0.1.0.0
github: "githubuser/arc-rest"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/alexa-api#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - wai
  - warp
  - process
  - bytestring
  - exceptions
  - typed-process
  - text
  - servant-swagger
  - swagger2
  - lens
  - wai-cors
  - servant-options == 0.1.0.0
  - http-types == 0.12.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  arc-rest:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - arc-rest
  arc-rest-swagger:
    main: Docs.hs
    source-dirs: swagger
    dependencies:
      - arc-rest == 0.1.0.0

tests:
  arc-rest-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - arc-rest
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
