version: "3.9"
services:
  arc-rest:
    ports:
      - 8080:80
    build:
      context: ../
      dockerfile: production/prod.dockerfile
    container_name: arc-rest
    volumes:
      - .:/arc-rest 
